apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  image: quay.io/keycloak/keycloak:24.0.5
  features:
    enabled:
      - preview
  db:
    vendor: dev-file
  http:
    httpEnabled: true
    httpPort: 8080
  hostname:
    hostname: localhost
    strict: false
    strictBackchannel: false
  resources:
    requests:
      memory: "768Mi"
      cpu: "250m"
    limits:
      memory: "1536Mi"
      cpu: "1000m"
  additionalOptions:
    - name: health-enabled
      value: "true"
    - name: legacy-observability-interface
      value: "true"
  unsupported:
    podTemplate:
      spec:
        containers:
          - name: keycloak
            env:
              - name: KC_JAVA_OPTS_APPEND
                value: "-Dvertx.cacheDirBase=/dev/shm/vertx-cache"
              - name: JAVA_OPTS_APPEND
                value: "-Dvertx.cacheDirBase=/dev/shm/vertx-cache"
            startupProbe:
              httpGet:
                path: /realms/master
                port: 8080
                scheme: HTTP
              failureThreshold: 600
              periodSeconds: 1
              successThreshold: 1
              timeoutSeconds: 5
